config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_battles/index'
  get 'pokemon_battles/new'
  get 'pokemon_battles/show'
  root 'static_pages#home'
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post :create_pokemon_skill, on: :member
    delete 'destroy_pokemon_skill/:skill_id', to: 'pokemons#destroy_pokemon_skill', as: "destroy_pokemon_skill", on: :member
  end
  get '/heal_all', to: 'pokemons#heal_all', as: "heal_pokemons"
  get '/heal/:id', to: 'pokemons#heal', as: "heal_pokemon"

  resources :pokemon_battles do
    get '/log', to: 'pokemon_battles#log', as: "show_battle_log", on: :member
    get '/auto_battle', to: 'pokemon_battles#auto_battle', as: "auto_battle", on: :member
  end

  resources :trainers do
    post :create_pokemon_trainer, on: :member
    delete 'destroy_pokemon_trainer/:pokemon_id', to: 'trainers#destroy_pokemon_trainer', as: "destroy_pokemon_trainer", on: :member
  end
end

app/models/pokemon_battle.rb
class PokemonBattle < ApplicationRecord
  extend Enumerize
  belongs_to :pokemon1, class_name: 'Pokemon'
  belongs_to :pokemon2, class_name: 'Pokemon'
  belongs_to :pokemon_winner, class_name: 'Pokemon', foreign_key: 'pokemon_winner_id', optional: true
  belongs_to :pokemon_loser, class_name: 'Pokemon', foreign_key: 'pokemon_loser_id', optional:true
  has_many  :pokemon_battle_logs, dependent: :destroy

  validate :pokemon_id_battle_must_be_different
  validate :pokemons_current_hp_must_greater_than_zero, on: :create
  validate :pokemon_id_ongoing_must_be_less_than_two, on: :create
  enumerize :state, in: [:ongoing, :finished]
  enumerize :battle_type, in: [:vs_ai, :auto, :manual]
  private

  def pokemon_id_battle_must_be_different
    if pokemon1_id == pokemon2_id
      errors.add(:pokemon_id, "can't be same!")
    end
  end

  def pokemons_current_hp_must_greater_than_zero
    if self.pokemon1.present? && self.pokemon2.present?

      if self.pokemon1.current_health_point < 1
        errors.add(:pokemon_1, "HP is zero")
      end

      if self.pokemon2.current_health_point < 1
        errors.add(:pokemon_2, "HP is zero")
      end

    end
  end

  def pokemon_id_ongoing_must_be_less_than_two

    if PokemonBattle.where(pokemon1_id: [self.pokemon1_id, self.pokemon2_id], state: "ongoing").count >=1 || PokemonBattle.where(pokemon2_id: [self.pokemon1_id, self.pokemon2_id], state: "ongoing").count >=1
      errors.add(:pokemon, "1 or Pokemon 2 still on going")
    end
  end


end

app/controllers/pokemon_battles_controller.rb
class PokemonBattlesController < ApplicationController
  include PokemonBattlesHelper

  def index
    @pokemon_battles = PokemonBattle.paginate(page: params[:page], per_page:5).order('created_at DESC')
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon Battle List", pokemon_battles_path, title: "Pokemon Battle List"
  end

  def new
    @pokemon_battle = PokemonBattle.new
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon Battle List", pokemon_battles_path, title: "Back to Pokemon Battle List"
    add_breadcrumb "New Pokemon Battle", new_pokemon_battle_path, title: "New Pokemon Battle"
  end

  def create
    @pokemon_battle = PokemonBattle.new(pokemon_battle_params)
    @pokemon_battle.battle_type = params[:commit]

    @pokemon_battle.current_turn = 1
    @pokemon_battle.state = "ongoing"

    if @pokemon_battle.pokemon1.present? && @pokemon_battle.pokemon1.present?
      @pokemon_battle.pokemon1_max_health_point = @pokemon_battle.pokemon1.max_health_point
      @pokemon_battle.pokemon2_max_health_point = @pokemon_battle.pokemon2.max_health_point
    end

    if @pokemon_battle.valid?

      if @pokemon_battle.pokemon1.pokemon_trainer.present?
        pokemon_trainer = @pokemon_battle.pokemon1.pokemon_trainer
        pokemon_trainer.battle_count = pokemon_trainer.battle_count + 1
        pokemon_trainer.save
      end
      @pokemon_battle.save
      if @pokemon_battle.battle_type == 'auto'
        autoBattleEngine = AiBattleEngine.new(@pokemon_battle)
        autoBattleEngine.auto_battle!
      end
      redirect_to pokemon_battle_path(@pokemon_battle)
    else
      render 'new'
    end
  end

  def show
    @pokemon_battle = PokemonBattle.find(params[:id])
    @options_for_skills1 = @pokemon_battle.pokemon1.skills.map do |skill| [skill.name, skill.id] end
    @options_for_skills2 = @pokemon_battle.pokemon2.skills.map do |skill| [skill.name, skill.id] end

    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon Battle List", pokemon_battles_path, title: "Back to Pokemon Battle List"
    add_breadcrumb "Battle", pokemon_battle_path(@pokemon_battle), title: "Pokemon Battle"

    @pokemon_battle.save

  end

  def destroy
    @pokemon_battles = PokemonBattle.find(params[:id])
    @pokemon_battles.destroy

    redirect_to pokemon_battles_path
  end

  def update
    @pokemon_battle = PokemonBattle.find(params[:id])
    commit = params[:commit]

    selectedSkill = params[:attack][:skill_id]
    pokemonId = params[:attack][:pokemon_id]
    battleEngine = BattleEngine.new(@pokemon_battle, pokemonId, commit, selectedSkill)

    if battleEngine.valid_next_turn?
      if battleEngine.next_turn!
        battleEngine.save!
        if @pokemon_battle.battle_type == "vs_ai" && @pokemon_battle.pokemon_winner_id.nil?
          aiTurn = AiBattleEngine.new(@pokemon_battle)
          aiTurn.ai_turn!
        end
        redirect_to pokemon_battle_path(@pokemon_battle)
      else
        flash.now[:danger] = battleEngine.errors.join("<br>").html_safe
        render 'show'
      end
    else
      flash.now[:danger] = battleEngine.errors.join("<br>").html_safe
      render 'show'
    end

  end

  def log
    @pokemon_battle_logs = PokemonBattleLog.where(pokemon_battle_id: params[:id])
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Battle", pokemon_battle_path(@pokemon_battle_logs.first.pokemon_battle_id), title: "Back to Pokemon Battle"
    add_breadcrumb "Battle Log"
  end

  def auto_battle
    @pokemon_battle = PokemonBattle.find(params[:id])
    @pokemon_battle.battle_type = "auto"
    autoBattleEngine = AiBattleEngine.new(@pokemon_battle)
    autoBattleEngine.auto_battle!

    redirect_to pokemon_battle_path(@pokemon_battle)
  end
end

app/helpers/pokemon_battles_helper.rb
module PokemonBattlesHelper
  def options_for_pokemon_id
    Pokemon.where("current_health_point > ?", 0).map do |p|
      [p.name, p.id]
    end
  end

  def pokemon_battle_params
    params.require(:pokemon_battle).permit(:pokemon1_id, :pokemon2_id)
  end
end

app/views/pokemon_battles/index.html.erb
<h1>Pokemon Battle</h1>

<br>
  <%= link_to "Create new battle", new_pokemon_battle_path, :class => "btn btn-primary mb-2" %>
<br>

<table class="table table-bordered mb-0">
  <thead class="thead-dark">
    <tr>
      <th>Pokemon 1</th>
      <th>Pokemon 2</th>
      <th>Turn</th>
      <th>Status</th>
      <th>Winner</th>
      <th>Experience Gained</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pokemon_battles.each do |pokemon_battle| %>
    <tr>
      <td> <%= link_to pokemon_battle.pokemon1.name, pokemon_path(pokemon_battle.pokemon1) %> </td>
      <td> <%= link_to pokemon_battle.pokemon2.name, pokemon_path(pokemon_battle.pokemon2) %> </td>
      <td> <%= pokemon_battle.current_turn %> </td>
      <td> <%= pokemon_battle.state %> </td>
      <td> <%= pokemon_battle.pokemon_winner.name if pokemon_battle.pokemon_winner.present? %> </td>
      <td> <%= pokemon_battle.experience_gain %> </td>
      <td id="action">
        <%= link_to "Battle", pokemon_battle_path(pokemon_battle), :class => "btn btn-primary" %>
        <%= link_to "Delete", pokemon_battle, method: :delete,
                                  data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-1" style="float: right">
  <%= will_paginate @pokemon_battles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/pokemon_battles/log.html.erb
<h1>Pokemon Battle Logs</h1>

<table class="table table-bordered mb-0">
  <thead class="thead-dark">
    <tr>
      <th>Attacker</th>
      <th>Defender</th>
      <th>Turn</th>
      <th>Attacker Current Health</th>
      <th>Defender Current Health</th>
      <th>Skill Used</th>
      <th>Damage</th>
      <th>Action Type</th>
    </tr>
  </thead>
  <tbody>
    <% @pokemon_battle_logs.each do |pokemon_battle_log| %>
    <tr>
      <td> <%= pokemon_battle_log.pokemon1.name %> </td>
      <td> <%= pokemon_battle_log.pokemon2.name %> </td>
      <td> <%= pokemon_battle_log.turn %> </td>
      <td> <%= pokemon_battle_log.attacker_current_health_point %> </td>
      <td> <%= pokemon_battle_log.defender_current_health_point %> </td>
      <td> <%= pokemon_battle_log.skill.name if pokemon_battle_log.skill.present? %> </td>
      <td> <%= pokemon_battle_log.damage %> </td>
      <td> <%= pokemon_battle_log.action_type %> </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/pokemon_battles/new.html.erb
<div class="col-centered mb-5"><h2>SELECT POKEMON</h2></div>

<%= form_for(@pokemon_battle, :html => {class: 'inline-form'}) do |f| %>

<% if @pokemon_battle.errors.present? %>
  <div class="alert alert-danger">
    <% @pokemon_battle.errors.full_messages.each do |error| %>
        <p> <%= error %></p>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-5">
    <%= f.label "Pokemon 1" %>
    <%= f.select :pokemon1_id, options_for_pokemon_id, {:prompt => "Select One"}, class: "form-control" %>
  </div>
  <div class="col-md-2 col-centered">
    <br><h1>VS</h1>

    <div class="col-md-12"><%= f.submit "vs_ai", class: "btn btn-primary mt-5 btn-block" %></div>
    <div class="col-md-12"><%= f.submit "auto", class: "btn btn-primary mt-2 btn-block" %></div>
    <div class="col-md-12" id="pvp"><%= f.submit "manual", class: "btn btn-primary mt-2 btn-block" %></div>

  </div>
  <div class="col-md-5">
    <%= f.label "Pokemon 2" %>
    <%= f.select :pokemon2_id, options_for_pokemon_id, {:prompt => "Select One"}, class: "form-control" %>
  </div>
</div>

<% end %>

app/views/pokemon_battles/show.html.erb
<%= link_to "View battle logs", show_battle_log_pokemon_battle_path(@pokemon_battle), :class => "btn btn-primary" %>
<% if @pokemon_battle.state != "finished" %>
  <%= link_to "Auto Battle",auto_battle_pokemon_battle_path(@pokemon_battle), :class => "btn btn-primary" %>
<% end %>
<center class="mb-5">
  <h1>Pokemon Battle</h1>
  <h4>State : <%= @pokemon_battle.state %></h4>
  <h4>Turn : <%= @pokemon_battle.current_turn %></h4>
</center>


<div class='row'>

    <div class="col-md-5 col-centered">
      <%= form_for(:attack, url: pokemon_battle_path(@pokemon_battle), method: :patch, :html => {class: 'inline-form'}) do |f| %>
      <%= f.hidden_field :pokemon_id, value: @pokemon_battle.pokemon1.id %>
        <h4 class="mb-3"><%= link_to @pokemon_battle.pokemon1.name, pokemon_path(@pokemon_battle.pokemon1) %></h4>
        <span class="ml-5"><%= image_tag(@pokemon_battle.pokemon1.pokedex.image_url, height: '300', width: '300') %> </span>
        <div class="row mb-3 mt-2">
          <div class="col-md-5">HP</div>
          <div class="col-md-2">:</div>
          <div class="col-md-5"><%= @pokemon_battle.pokemon1.current_health_point %> / <%= @pokemon_battle.pokemon1_max_health_point %></div>
        </div>
        <% if @pokemon_battle.current_turn % 2 != 0 && @pokemon_battle.state != "finished" %>
          <div class="row mb-3">
            <div class="col-md-5">Skill</div>
            <div class="col-md-2">:</div>
            <div class="col-md-5"><%= f.select :skill_id, @pokemon_battle.pokemon1.pokemon_skills.map { |pokemon_skill| [pokemon_skill.skill.name + " (" + pokemon_skill.current_pp.to_s + " / " + pokemon_skill.skill.max_pp.to_s + ")", pokemon_skill.skill_id] }, {prompt: "Select Skill"}, class: "form-control" %></div>
          </div>
          <div class="row mb-3">
            <div class="col-md-12">
                <%= f.submit "Attack", class: "btn btn-primary" %>
                <%= f.submit "Surrender", class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>


  <div class="col-md-2"></div>


  <div class="col-md-5 col-centered">
    <%= form_for(:attack, url: pokemon_battle_path(@pokemon_battle), method: :patch, :html => {class: 'inline-form'}) do |f| %>
    <%= f.hidden_field :pokemon_id, value: @pokemon_battle.pokemon2.id %>
      <h4 class="mb-3"><%= link_to @pokemon_battle.pokemon2.name, pokemon_path(@pokemon_battle.pokemon2) %></h4>
      <span class="ml-5"><%= image_tag(@pokemon_battle.pokemon2.pokedex.image_url, height: '300', width: '300') %> </span>
      <div class="row mb-3 mt-2">
        <div class="col-md-5">HP</div>
        <div class="col-md-2">:</div>
        <div class="col-md-5"><%= @pokemon_battle.pokemon2.current_health_point %> / <%= @pokemon_battle.pokemon2_max_health_point %></div>
      </div>
      <% if @pokemon_battle.current_turn % 2 == 0 && @pokemon_battle.state != "finished" %>
        <div class="row mb-3">
          <div class="col-md-5">Skill</div>
          <div class="col-md-2">:</div>
          <div class="col-md-5"><%= f.select :skill_id, @pokemon_battle.pokemon2.pokemon_skills.map { |pokemon_skill| [pokemon_skill.skill.name + " (" + pokemon_skill.current_pp.to_s + " / " + pokemon_skill.skill.max_pp.to_s + ")", pokemon_skill.skill_id] }, {prompt: "Select Skill"}, class: "form-control" %></div>
        </div>
        <div class="row mb-3">
          <div class="col-md-12">
              <%= f.submit "Attack", class: "btn btn-primary" %>
              <%= f.submit "Surrender", class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>
<br>
<h3>
<center>
  <% if @pokemon_battle.state=="finished"%>
  <p class="bg-primary text-white mb-0"><%= Pokemon.find_by(id: @pokemon_battle.pokemon_winner_id).name %> Win! </p>
  <p class="bg-danger text-white"><%= Pokemon.find_by(id: @pokemon_battle.pokemon_loser_id).name %> Lose </p>
  <% end %>
</center>
</h3>