config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_battles/index'
  get 'pokemon_battles/new'
  get 'pokemon_battles/show'
  root 'static_pages#home'
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post :create_pokemon_skill, on: :member
    delete 'destroy_pokemon_skill/:skill_id', to: 'pokemons#destroy_pokemon_skill', as: "destroy_pokemon_skill", on: :member
  end
  get '/heal_all', to: 'pokemons#heal_all', as: "heal_pokemons"
  get '/heal/:id', to: 'pokemons#heal', as: "heal_pokemon"

  resources :pokemon_battles do
    get '/log', to: 'pokemon_battles#log', as: "show_battle_log", on: :member
    get '/auto_battle', to: 'pokemon_battles#auto_battle', as: "auto_battle", on: :member
  end

  resources :trainers do
    post :create_pokemon_trainer, on: :member
    delete 'destroy_pokemon_trainer/:pokemon_id', to: 'trainers#destroy_pokemon_trainer', as: "destroy_pokemon_trainer", on: :member
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :pokedex
  has_one :pokemon_trainer
  has_one :trainer

  has_many :pokemon_skills
  has_many :skills, through: :pokemon_skills
  has_many :pokemon_battles, class_name: 'PokemonBattle', foreign_key: 'pokemon1_id'
  has_many :pokemon_battles, class_name: 'PokemonBattle', foreign_key: 'pokemon2_id'

  has_many :wins, class_name: 'PokemonBattle', foreign_key: 'pokemon_winner_id'
  has_many :loses, class_name: 'PokemonBattle', foreign_key: 'pokemon_loser_id'

  has_many :pokemon_battle_logs, class_name: 'PokemonBattleLog', foreign_key: 'pokemon1_id'
  has_many :pokemon_battle_logs, class_name: 'PokemonBattleLog', foreign_key: 'pokemon2_id'

  validates :name, presence: true, uniqueness: {scope: [:pokedex_id]}, length: {maximum: 45}
  validates :pokedex_id, presence: true

  validates :max_health_point, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :current_health_point, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :current_health_point, numericality: { only_integer: true, less_than_or_equal_to: :max_health_point }, if: :max_health_point_present?
  validates :current_experience, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :attack, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :defence, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :speed, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :level, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  private

  def max_health_point_present?
    max_health_point.present?
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  include PokemonsHelper
  def index
    @pokemons = Pokemon.order(id: :asc).paginate(page: params[:page], per_page:5)
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon List", pokemons_path, title: "Pokemon List"
  end

  def new
    @pokemon = Pokemon.new
    @pokemon_skills = PokemonSkill.new
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon List", pokemons_path, title: "Back to Pokemon List"
    add_breadcrumb "New Pokemon", new_pokemon_path, title: "New Pokemon"
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)

    @pokemon.max_health_point = @pokemon.pokedex.base_health_point
    @pokemon.current_health_point = @pokemon.pokedex.base_health_point
    @pokemon.attack = @pokemon.pokedex.base_attack
    @pokemon.defence = @pokemon.pokedex.base_defence
    @pokemon.speed = @pokemon.pokedex.base_speed

    if @pokemon.valid?
      @pokemon.save
      flash[:success] = "Pokemon #{@pokemon.name} created!"
      redirect_to pokemon_path(@pokemon)
    else
      render 'new'
    end
  end

  def create_pokemon_skill
    @pokemon_skills = PokemonSkill.new(pokemon_skill_params)
    @pokemon = Pokemon.find(params[:id])
    if params[:pokemon_skill][:skill_id].present?
      @pokemon_skills.pokemon_id = params[:id]
      @pokemon_skills.current_pp = @pokemon_skills.skill.max_pp

      if @pokemon_skills.save
        flash[:success] = "Pokemon Skill #{@pokemon_skills.skill.name} Added!"
        redirect_to pokemon_path(params[:id])
      else
        @options_for_skills = Skill.where(element_type: @pokemon.pokedex.element_type).map do |p|
          [p.name, p.id]
        end
        render 'show'
      end

    else
      @options_for_skills = Skill.where(element_type: @pokemon.pokedex.element_type).map do |p|
          [p.name, p.id]
        end
        flash.now[:danger] = "Skill cannot be empty"
        render 'show'
    end

  end

  def destroy_pokemon_skill
    @pokemon_skills = PokemonSkill.find_by(pokemon_id: params[:id], skill_id: params[:skill_id])
    @pokemon_skills.destroy
    flash[:success] = "Pokemon Skill #{@pokemon_skills.skill.name} Destroyed!"
    redirect_to pokemon_path(@pokemon_skills.pokemon_id)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @pokemon_skills = PokemonSkill.new

    @options_for_skills = Skill.where(element_type: @pokemon.pokedex.element_type).map do |p|
      [p.name, p.id]
    end
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon List", pokemons_path, title: "Back to Pokemon List"
    add_breadcrumb @pokemon.name, pokemon_path(@pokemon)
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Pokemon List", pokemons_path, title: "Back to Pokemon List"
    add_breadcrumb @pokemon.name, edit_pokemon_path(@pokemon)
  end

  def update
    @pokemon = Pokemon.find(params[:id])

    if @pokemon.update_attributes(pokemon_edit_params)
      flash[:success] = "Pokemon #{@pokemon.name} updated!"
      redirect_to pokemon_path(@pokemon)
    else
      render 'edit'
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy
    flash[:success] = "Pokemon #{@pokemon.name} deleted!"
    redirect_to pokemons_path
  end

  def heal_all
    pokemonOnGoing = []
    PokemonBattle.where(state: "ongoing").each do |p|
      pokemonOnGoing << p.pokemon1.id
      pokemonOnGoing << p.pokemon2.id
    end
    pokemonsHealedId = Pokemon.all.ids - pokemonOnGoing
    pokemonsHealedId.each do |id|
      pokemonsHealed = Pokemon.find(id)
      pokemonsHealed.current_health_point = Pokemon.find(id).max_health_point

      pokemonsHealed.pokemon_skills.each do |pokemon_skill|
        pokemon_skill.current_pp = pokemon_skill.skill.max_pp
        pokemon_skill.save
      end
      pokemonsHealed.save
    end
    flash[:success] = "All Pokemon Healed Up!"
    redirect_to pokemons_path
  end

  def heal
    @pokemon = Pokemon.find(params[:id])
    pokemon1IdList = PokemonBattle.where(state: "ongoing").map do |pokemon|
      pokemon.pokemon1_id
    end
    pokemon2IdList = PokemonBattle.where(state: "ongoing").map do |pokemon|
      pokemon.pokemon2_id
    end

    if !pokemon1IdList.include?(@pokemon.id) && !pokemon2IdList.include?(@pokemon.id)
      @pokemon.current_health_point = @pokemon.max_health_point

      @pokemon.pokemon_skills.each do |pokemon_skill|
        pokemon_skill.current_pp = pokemon_skill.skill.max_pp
        pokemon_skill.save
      end
      @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      @pokemon_skills = PokemonSkill.new
       @options_for_skills = Skill.where(element_type: @pokemon.pokedex.element_type).map do |p|
         [p.name, p.id]
       end
      flash.now[:danger] = "Pokemon still in ongoing battle"
      render 'show'
    end
  end

end

app/helpers/pokemons_helper.rb
module PokemonsHelper
  def pokemon_params
    params.require(:pokemon).permit(:name, :pokedex_id)
  end

  def pokemon_edit_params
    params.require(:pokemon).permit(:max_health_point, :current_health_point, :attack, :defence, :speed)
  end

  def pokemon_skill_params
    params.require(:pokemon_skill).permit(:skill_id)
  end

  def options_for_pokedex_id
    Pokedex.all.map do |p|
      [p.name, p.id]
    end
  end

  def options_for_skill

  end
end

app/views/pokemons/_form.html.erb
<br>
<%= form_for(@pokemon, :html => {class: 'inline-form'}) do |f| %>
<% if @pokemon.errors.present? %>
  <div class="alert alert-danger">
    <% @pokemon.errors.full_messages.each do |error| %>
        <p> <%= error %></p>
    <% end %>
  </div>
<% end %>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :name %></div>
    <div class="col-md-9"> <%= f.text_field :name, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :pokedex_id %></div>
    <div class="col-md-9"> <%= f.select :pokedex_id, options_for_pokedex_id, {}, class: "form-control" %></div>
  </div>

  <span><%= f.submit 'Save', class: "btn btn-primary mr-2" %></span>



<% end %>

app/views/pokemons/edit.html.erb
<h2>Edit Pokemon</h2>
<br>
<%= form_for(@pokemon, :html => {class: 'inline-form'}) do |f| %>
  <% if @pokemon.errors.present? %>
    <div class="alert alert-danger">
      <% @pokemon.errors.full_messages.each do |error| %>

          <p> <%= error %></p>

      <% end %>
    </div>
  <% end %>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :pokedex_id %></div>
    <div class="col-md-9"> <%= @pokemon.pokedex.name %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :level %></div>
    <div class="col-md-9"> <%= @pokemon.level %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :current_experience %></div>
    <div class="col-md-9"> <%= @pokemon.current_experience %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :max_health_point %></div>
    <div class="col-md-9"> <%= f.text_field :max_health_point, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :current_health_point %></div>
    <div class="col-md-9"> <%= f.text_field :current_health_point, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :attack %></div>
    <div class="col-md-9"> <%= f.text_field :attack, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :defence %></div>
    <div class="col-md-9"> <%= f.text_field :defence, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :speed %></div>
    <div class="col-md-9"> <%= f.text_field :speed, class: "form-control" %></div>
  </div>

  <span><%= f.submit 'Save', class: "btn btn-primary mr-2" %></span>



<% end %>

app/views/pokemons/index.html.erb
<h2>Pokemon List</h2>

<br>
  <%= link_to "Create new pokemon", new_pokemon_path, :class => "btn btn-primary mb-2" %>

  <%= link_to "Heal all", heal_pokemons_path, :class => "btn btn-success mb-2" %>

<table class="table table-bordered mb-0">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Max Health Point</th>
      <th>Current Health Point</th>
      <th>Attack</th>
      <th>Defence</th>
      <th>Speed</th>
      <th>Current Experience</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pokemons.each do |pokemon| %>
    <tr>
      <td><%= link_to pokemon.name, pokemon_path(pokemon) %> </td>
      <td> <%= pokemon.level %> </td>
      <td> <%= pokemon.max_health_point %> </td>
      <td> <%= pokemon.current_health_point %> </td>
      <td> <%= pokemon.attack %> </td>
      <td> <%= pokemon.defence %> </td>
      <td> <%= pokemon.speed %> </td>
      <td> <%= pokemon.current_experience %> </td>
      <td> <%= image_tag(pokemon.pokedex.image_url, height: 30, width: 30) %> </td>
      <td id="action">
        <%= link_to "edit", edit_pokemon_path(pokemon), :class => "btn btn-primary" %>
        <%= link_to "delete", pokemon, method: :delete,
                                  data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
        <%= link_to "heal", heal_pokemon_path(pokemon), :class => "btn btn-success mt-1" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-1" style="float: right">
  <%= will_paginate @pokemons, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/pokemons/new.html.erb
<h2>New pokemon</h2>

<%= render 'form' %>

app/views/pokemons/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to "Heal", heal_pokemon_path(@pokemon), class: "btn btn-success" %>
    <%= link_to "Edit", edit_pokemon_path(@pokemon), class: "btn btn-primary" %>
    <%= link_to "Delete", @pokemon, method: :delete,
                                  data: { confirm: "You sure?" }, class: "btn btn-danger" %>
    <br><br>
    <div class="row">
      <div class="col-md-6"><%= image_tag(@pokemon.pokedex.image_url, height: '400', width: '400') %></div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <h3> <%= @pokemon.name  %> </h3>
          </div>
        <br>
          <div class="col-md-12">
            <div class="row mb-3">
              <div class="col-md-6">Elemenet Type :</div>
              <div class="col-md-6"> <%= @pokemon.pokedex.element_type %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Level :</div>
              <div class="col-md-6"> <%= @pokemon.level %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Max Health Point :</div>
              <div class="col-md-6"> <%= @pokemon.max_health_point %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Current Health Point :</div>
              <div class="col-md-6"> <%= @pokemon.current_health_point %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Attack :</div>
              <div class="col-md-6"> <%= @pokemon.attack %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Defence :</div>
              <div class="col-md-6"> <%= @pokemon.defence %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Speed :</div>
              <div class="col-md-6"> <%= @pokemon.speed %></div>
            </div>

            <div class="row mb-3">
              <div class="col-md-6">Current Experience :</div>
              <div class="col-md-6"> <%= @pokemon.current_experience %></div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <% if @pokemon_skills.errors.present? %>
      <div class="alert alert-danger">
        <% @pokemon_skills.errors.full_messages.each do |error| %>
            <p> <%= error %></p>
        <% end %>
      </div>
    <% end %>

    <div class="row">

      <div class="col-md-12">
        <%= form_for(:pokemon_skill, url: create_pokemon_skill_pokemon_path(@pokemon), :html => {class: 'inline-form'}) do |f| %>
          <div class="row mb-3 mt-3">
            <div class="col-md-1"><%= f.label "Add Skill", class: "pt-2"%></div>
            <div class="col-md-4"><%= f.select :skill_id, @options_for_skills, {prompt: "Select Skill"}, class: "form-control" %></div>
            <div class="col-md-1"><%= f.submit "Save", class: "btn btn-primary"%></div>
          </div>
        <% end %>

        <table class="table table-bordered mb-0 mt-2">
          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <th>Current PP</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @pokemon.pokemon_skills.each do |pokemon_skill| %>
            <tr>
              <td><%= pokemon_skill.skill.name %></td>
              <td><%= pokemon_skill.current_pp %> / <%= pokemon_skill.skill.max_pp %></td>
              <td><%= link_to "delete", destroy_pokemon_skill_pokemon_path(pokemon_skill.pokemon_id, pokemon_skill.skill_id), method: :delete,
                                  data: { confirm: "You sure?" }, :class => "btn btn-danger" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>

  </div>
  <div class="col-md-12 col-centered mt-5">
    <h3>Win Lose Ratio</h3>
    <div class="card-body"><%= pie_chart Statistic.win_lose_ratio_by_pokemon(@pokemon.id), label: "Value" %></div>
  </div>
</div>