config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_battles/index'
  get 'pokemon_battles/new'
  get 'pokemon_battles/show'
  root 'static_pages#home'
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post :create_pokemon_skill, on: :member
    delete 'destroy_pokemon_skill/:skill_id', to: 'pokemons#destroy_pokemon_skill', as: "destroy_pokemon_skill", on: :member
  end
  get '/heal_all', to: 'pokemons#heal_all', as: "heal_pokemons"
  get '/heal/:id', to: 'pokemons#heal', as: "heal_pokemon"

  resources :pokemon_battles do
    get '/log', to: 'pokemon_battles#log', as: "show_battle_log", on: :member
    get '/auto_battle', to: 'pokemon_battles#auto_battle', as: "auto_battle", on: :member
  end

  resources :trainers do
    post :create_pokemon_trainer, on: :member
    delete 'destroy_pokemon_trainer/:pokemon_id', to: 'trainers#destroy_pokemon_trainer', as: "destroy_pokemon_trainer", on: :member
  end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokemon_trainers
  has_many :pokemons, through: :pokemon_trainers

  validates :email, uniqueness: {:case_sensitive => false}, presence: true
  has_secure_password
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  include TrainersHelper

  def index
    @trainers = Trainer.paginate(page: params[:page], per_page:5)
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Trainers", trainers_path, title: "Trainer List"
  end

  def new
    @trainer = Trainer.new
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Trainers", trainers_path, title: "Back to Trainer List"
    add_breadcrumb "New Trainer", new_trainer_path, title: "Create New trainer"
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      flash[:success] = "Trainer '#{@trainer.name}' created!"
      redirect_to trainer_path(@trainer)
    else
      render 'new'
    end
  end

  def show
    @trainer = Trainer.find(params[:id])
    @pokemon_trainer = PokemonTrainer.new
    add_breadcrumb "Home", root_path, title: "Back to Home"
    add_breadcrumb "Trainer List", trainers_path, title: "Back to Trainer List"
    add_breadcrumb @trainer.name, trainer_path(@trainer)
  end

  def create_pokemon_trainer
    @pokemon_trainer = PokemonTrainer.new(pokemon_trainer_params)
    @trainer = Trainer.find(params[:id])
    if params[:pokemon_trainer][:pokemon_id].present?
      @pokemon_trainer.pokemon_id = params[:pokemon_trainer][:pokemon_id]
      @pokemon_trainer.trainer_id = @trainer.id

      if @pokemon_trainer.save
        flash[:success] = "Pokemon #{@pokemon_trainer.pokemon.name} Added!"
        redirect_to trainer_path(@trainer)
      else
        render 'show'
      end

    else
        flash.now[:danger] = "Skill cannot be empty"
        render 'show'
    end
  end

  def destroy_pokemon_trainer
    @pokemon_trainer = PokemonTrainer.find_by(pokemon_id: params[:id], pokemon_id: params[:pokemon_id])
    @pokemon_trainer.destroy
    flash[:success] = "Pokemon #{@pokemon_trainer.pokemon.name} Destroyed!"
    redirect_to trainer_path(@pokemon_trainer.trainer_id)
  end

end

app/helpers/trainers_helper.rb
module TrainersHelper
  def trainer_params
    params.require(:trainer).permit(:name, :email, :password_digest)
  end

  def pokemon_trainer_params
    params.require(:pokemon_trainer).permit(:pokemon_id)
  end
end

app/views/trainers/_form.html.erb
<br>
<%= form_for(@trainer, :html => {class: 'inline-form'}) do |f| %>
<% if @trainer.errors.present? %>
  <div class="alert alert-danger">
    <% @trainer.errors.full_messages.each do |error| %>

        <p> <%= error %></p>

    <% end %>
  </div>
<% end %>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :name %></div>
    <div class="col-md-9"> <%= f.text_field :name, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :email %></div>
    <div class="col-md-9"> <%= f.text_field :email, class: "form-control" %></div>
  </div>

  <div class="row mb-3">
    <div class="col-md-3"><%= f.label :password_digest %></div>
    <div class="col-md-9"> <%= f.password_field :password_digest, class: "form-control" %></div>
  </div>

  <span><%= f.submit 'Save', class: "btn btn-primary mr-2" %></span>

<% end %>

app/views/trainers/index.html.erb
<h2>Trainer List</h2>

<br>
  <%= link_to "Create new trainer", new_trainer_path, :class => "btn btn-primary mb-2" %>
<br>

<table class="table table-bordered mb-0">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @trainers.each do |trainer| %>
    <tr>
      <td><%= link_to trainer.name, trainer_path(trainer) %> </td>
      <td> <%= trainer.email %> </td>
      <td id="action">
        <%= link_to "delete", trainer, method: :delete,
                                  data: { confirm: "You sure?" }, :class => "btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-1" style="float: right">
  <%= will_paginate @trainers, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/trainers/new.html.erb
<h2>Create new trainer</h2>

<%= render 'form' %>

app/views/trainers/show.html.erb
<br>
<h2><%= @trainer.name %></h2>
<br>
<p>Email : <%= @trainer.email %></p>

<% if @pokemon_trainer.errors.present? %>
      <div class="alert alert-danger">
        <% @pokemon_trainer.errors.full_messages.each do |error| %>
            <p> <%= error %></p>
        <% end %>
      </div>
    <% end %>

<div class="row">

  <div class="col-md-12">
    <%= form_for(:pokemon_trainer, url: create_pokemon_trainer_trainer_path(@trainer), :html => {class: 'inline-form'}) do |f| %>
      <div class="row mb-3 mt-3">
        <div class="col-md-1 text-center"><%= f.label "Add pokemon", class: ""%></div>
        <div class="col-md-4"><%= f.select :pokemon_id, Pokemon.all.map { |p| [p.name, p.id] }, {prompt: "Select Pokemon"}, class: "form-control" %></div>
        <div class="col-md-1"><%= f.submit "Save", class: "btn btn-primary"%></div>
      </div>
    <% end %>

    <table class="table table-bordered mb-0 mt-2">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @trainer.pokemon_trainers.each do |pokemon_trainer| %>
        <tr>
          <td><%= link_to pokemon_trainer.pokemon.name, pokemon_path(pokemon_trainer.pokemon) %></td>
          <td><%= link_to "delete", destroy_pokemon_trainer_trainer_path(pokemon_trainer.trainer_id, pokemon_trainer.pokemon_id), method: :delete,
                              data: { confirm: "You sure?" }, :class => "btn btn-danger" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<div class="row mt-4">
  <div class="col-md-6">
    <div id="container" style="width: 500px; height: 400px; margin: 0 auto">
      <div class="card">
        <div class="card-header text-center">Most Chosen Pokemon to Battle</div>
        <div class="card-body"><%= column_chart Statistic.most_chosen_pokemon_to_battle_by_trainer(@trainer.id), label: "Value" %></div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
        <div class="card-header text-center">Pokemon Win Rate</div>
        <div class="card-body"><%= bar_chart Statistic.pokemon_win_rate_by_trainer(@trainer.id), label: "Value", suffix: "%"  %></div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-md-6">
    <div id="container" style="width: 500px; height: 400px; margin: 0 auto">
      <div class="card">
        <div class="card-header text-center">Pokemon Most Win</div>
        <div class="card-body"><%= line_chart Statistic.most_win_by_pokemon_trainer(@trainer.id) %></div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="card">
      <div class="card-header text-center">Pokemon Most Lose</div>
      <div class="card-body"><%= line_chart Statistic.most_lose_by_pokemon_trainer(@trainer.id), label: "Value" %>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-md-12">
    <div class="card">
        <div class="card-body"><%= pie_chart Statistic.pokemon_percentage_by_pokemon_trainer(@trainer.id), title: 'Element Type of Pokemon Percentage', label: "Value", suffix: "%" %>
        </div>
    </div>
  </div>
</div>