config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_battles/index'
  get 'pokemon_battles/new'
  get 'pokemon_battles/show'
  root 'static_pages#home'
  resources :pokedexes
  resources :skills
  resources :pokemons do
    post :create_pokemon_skill, on: :member
    delete 'destroy_pokemon_skill/:skill_id', to: 'pokemons#destroy_pokemon_skill', as: "destroy_pokemon_skill", on: :member
  end
  get '/heal_all', to: 'pokemons#heal_all', as: "heal_pokemons"
  get '/heal/:id', to: 'pokemons#heal', as: "heal_pokemon"

  resources :pokemon_battles do
    get '/log', to: 'pokemon_battles#log', as: "show_battle_log", on: :member
    get '/auto_battle', to: 'pokemon_battles#auto_battle', as: "auto_battle", on: :member
  end

  resources :trainers do
    post :create_pokemon_trainer, on: :member
    delete 'destroy_pokemon_trainer/:pokemon_id', to: 'trainers#destroy_pokemon_trainer', as: "destroy_pokemon_trainer", on: :member
  end
end

app/views/layouts/_footer.html.erb
<br>
<footer class="page-footer bg-secondary">
  <div class="container" style="height:50px; position: relative;">
    <center><span class="text-white content">Copyright &copy; Ivan 2018</span></center>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark " id="mainNav">

    <%= link_to "Pokemon Game", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Battle", pokemon_battles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pokemon", pokemons_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pokedex", pokedexes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Skills", skills_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Trainer", trainers_path, class: "nav-link" %>
        </li>
      </ul>
    </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonRainbow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="holder" class="container">
      <ol class="breadcrumb">
        <%= render_breadcrumbs tag: :li, separator: "&nbsp / &nbsp" %>
      </ol>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>
  </body>

</html>